/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package theball;

import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.Random;

/**
 *
 * @author duyha
 */
@SuppressWarnings("serial")
public final class MyGamePanel extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form MyGamePanel
     */
    public MyGamePanel() {
        initComponents();
        newPaddles();
        newBall(1);
        newItem();
        newUIGame();
        this.setFocusable(true);
        this.setPreferredSize(SCREEN_SIZE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(255, 102, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    static final int GAME_WIDTH = 1000;
    static final int GAME_HEIGHT = (int) (GAME_WIDTH * (0.6));
    static final int BALL_DIAMETER = 30;
    static final int ITEM_SIZE = 20;
    static final int PADDLE_WIDTH = 25;
    static final int PADDLE_HEIGHT = 100;
    static final int playerspeed = 15;
    static final int botspeed = 12;
    static final Dimension SCREEN_SIZE = new Dimension(GAME_WIDTH, GAME_HEIGHT);
    static final Random rand = new Random();
    private boolean paused, botplayer1, botplayer2;
    private Item item;
    private Thread gameThread;
    private Image image;
    private Graphics graphics;
    private Paddle paddle1;
    private Paddle paddle2;
    private Ball ball;
    private UIGame uiGame;

    public void newBall(int id) {
        ball = new Ball(GAME_WIDTH / 2 - BALL_DIAMETER / 2, GAME_HEIGHT / 2 - BALL_DIAMETER / 2, BALL_DIAMETER,
                BALL_DIAMETER, id);
    }

    public void newPaddles() {
        if (botplayer1) {
            paddle1 = new Paddle(0, (GAME_HEIGHT / 2) - (PADDLE_HEIGHT / 2), PADDLE_WIDTH, PADDLE_HEIGHT, 1, botspeed);
        } else {
            paddle1 = new Paddle(0, (GAME_HEIGHT / 2) - (PADDLE_HEIGHT / 2), PADDLE_WIDTH, PADDLE_HEIGHT, 1,
                    playerspeed);
            this.addKeyListener(new MyGameKeyAdapter(paddle1));
        }
        if (botplayer2) {
            paddle2 = new Paddle(GAME_WIDTH - PADDLE_WIDTH, (GAME_HEIGHT / 2) - (PADDLE_HEIGHT / 2), PADDLE_WIDTH,
                    PADDLE_HEIGHT, 0, botspeed);
        } else {
            paddle2 = new Paddle(GAME_WIDTH - PADDLE_WIDTH, (GAME_HEIGHT / 2) - (PADDLE_HEIGHT / 2), PADDLE_WIDTH,
                    PADDLE_HEIGHT, 0, playerspeed);
            this.addKeyListener(new MyGameKeyAdapter(paddle2));
        }
    }

    public void newItem() {
        item = new Item(rand.nextInt(GAME_WIDTH / 4, 3 * GAME_WIDTH / 4 - ITEM_SIZE), rand.nextInt(GAME_HEIGHT - ITEM_SIZE), ITEM_SIZE, ITEM_SIZE);
    }

    public void newUIGame() {
        uiGame = new UIGame();
    }

    @Override
    public void paint(Graphics grap) {
        image = createImage(getWidth(), getHeight());
        graphics = image.getGraphics();
        draw(graphics);
        grap.drawImage(image, 0, 0, this);
    }

    public void draw(Graphics grap) {
        uiGame.draw(grap);
        paddle1.draw(grap);
        paddle2.draw(grap);
        ball.draw(grap);
        item.draw(grap);
        Toolkit.getDefaultToolkit().sync();
    }

    public void update() {
        paddle1.update();
        paddle2.update();
        ball.update();
        collisionEvent();
        uiGame.update();
        if (uiGame.winnerid != -1) {
            pausegame();
        }
    }

    public void botUpdate() {
        double dist;
        if (botplayer1) {
            if (ball.getCenterX() < GAME_WIDTH / 2) {
                dist = paddle1.getCenterY() - ball.getCenterY();
            } else {
                dist = paddle1.getCenterY() - GAME_HEIGHT / 2;
            }
            if (dist < -paddle1.height / 3) {
                paddle1.keyPressed(KeyEvent.VK_A);
            } else if (dist > paddle1.height / 3) {
                paddle1.keyPressed(KeyEvent.VK_Q);
            } else {
                paddle1.keyReleased();
            }
        }
        if (botplayer2) {
            if (ball.getCenterX() > GAME_WIDTH / 2) {
                dist = paddle2.getCenterY() - ball.getCenterY();
            } else {
                dist = paddle2.getCenterY() - GAME_HEIGHT / 2;
            }
            if (dist < -paddle2.height / 3) {
                paddle2.keyPressed(KeyEvent.VK_DOWN);
            } else if (dist > paddle2.height / 3) {
                paddle2.keyPressed(KeyEvent.VK_UP);
            } else {
                paddle2.keyReleased();
            }
        }
    }

    public void collisionEvent() {
        if (ball.y <= 0 || ball.y >= GAME_HEIGHT - BALL_DIAMETER) {
            ball.setYDirection(-ball.getYDirection());
        }
        if (ball.intersects(paddle1) || ball.intersects(paddle2)) {
            ball.addmoreSpeed();
            if (ball.intersects(paddle2)) {
                ball.setXDirection(-ball.getXDirection());
                item.update(0);
                paddle2.subPaddle();
                uiGame.player2score++;
            } else {
                item.update(1);
                paddle1.subPaddle();
                uiGame.player1score++;
            }
            if (!item.isAlive()) {
                newItem();
            }
        }
        if (!item.isHidden() && ball.intersects(item)) {
            if (item.getId() == 1) {
                paddle1.addPaddle();
            } else {
                paddle2.addPaddle();
            }
            newItem();
        }
        if (paddle1.y <= 0) {
            paddle1.y = 0;
        }
        if (paddle1.y >= (GAME_HEIGHT - PADDLE_HEIGHT)) {
            paddle1.y = GAME_HEIGHT - PADDLE_HEIGHT;
        }
        if (paddle2.y <= 0) {
            paddle2.y = 0;
        }
        if (paddle2.y >= (GAME_HEIGHT - PADDLE_HEIGHT)) {
            paddle2.y = GAME_HEIGHT - PADDLE_HEIGHT;
        }
        if (ball.x <= 0 || ball.x >= GAME_WIDTH - BALL_DIAMETER) {
            if (ball.x <= 0) {
                uiGame.player2score += 3;
                newBall(0);
            } else {
                uiGame.player1score += 3;
                newBall(1);
            }
            newItem();
        }
    }

    @Override
    public void run() {
        long lastTime = System.nanoTime();
        double amountOfTicks = 60;
        double ns = 1000000000 / amountOfTicks;
        double delta = 0;
        while (gameThread.isAlive()) {
            long now = System.nanoTime();
            delta += (now - lastTime) / ns;
            lastTime = now;
            if (delta >= 1) {
                if (!paused) {
                    botUpdate();
                    update();
                    repaint();
                }
                delta--;
            }
        }
    }

    /**
     *
     * @param bot1player
     * @param bot2player
     */
    public void playnewgame(boolean bot1player, boolean bot2player) {
        botplayer1 = bot1player;
        botplayer2 = bot2player;
        newPaddles();
        newBall(1);
        newItem();
        newUIGame();
        if (gameThread != null) {
            gameThread.interrupt();
        }
        gameThread = new Thread(this);
        paused = false;
        gameThread.start();
    }

    public void pausegame() {
        if (gameThread != null) {
            paused = !(paused);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
